export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL'
export const REMOVE_MESSAGES_FROM_CATEGORY = 'REMOVE_MESSAGES_FROM_CATEGORY'
